import Navbar from "../components/Navbar";
import "../styles/globals.css";
import Head from "next/head";
import Footer from "../components/Footer";
import Image from "next/image";
import whatsapp from "../public/icons/whatsapp.svg";
import Link from "next/link";
Link;
function MyApp({ Component, pageProps }) {
  return (
    <div className="">
      <Head>
        <title>Notaría Guerra Salas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link
        target="_blank"
        href={
          "https://api.whatsapp.com/send/?phone=51949881710&text&type=phone_number&app_absent=0"
        }
        className="fixed bottom-4 right-4 cursor-pointer z-20 "
      >
        <Image alt="whatsapp_icon" src={whatsapp} className="w-12 md:w-14" />
      </Link>
      <Navbar />
      <main className="overflow-hidden flex relative items-center min-h-[100vh] flex-col ">
        <Component {...pageProps} />
      </main>

      <Footer />
    </div>
  );
}

export default MyApp;
